profile_id: planning-behavior-profile-v1
status: APPROVED
owner_role: principal_architect
approval_owner: platform_lead
approval_status: APPROVED
plan_storage_mode: per-story-files
plan_directory: docs/plans
plan_index_file: docs/plans/index.md
plan_story_file_pattern: PLAN-{id}-{slug}.md
plan_traceability_required: true

topology:
  default: dependency-driven
  allowed_values:
    - single-repo
    - multi-repo
  service_per_repo_best_practice: true
  service_per_repo_exception_requires_adr: true

contracts:
  contract_first_required: true
  require_openapi_for_http: true
  ownership_required: true
  versioning_policy_required: true

workstreams:
  split_steps_required: true
  dependency_graph_required: true
  concurrent_execution_allowed: true
  execution_requires_dependency_satisfaction: true

reviews:
  code_review_feedback_loop_required: true
  developer_remediation_response_required: true
  coding_principles_required:
    - SOLID
    - DRY
    - clear_naming
    - explicit_error_handling
    - testability

integration:
  orchestration_step_allowed: true
  orchestration_requires_all_prerequisites_passed: true
  integration_feedback_loop_required: true

evidence:
  planning_behavior_resolution_required: true
  mcp_usage_evidence_required: true
  ai_usage_metrics_required_when_available: true

storage:
  strategy_required: true
  primary_system_of_record: relational-db
  cache_policy_required: true
  object_storage_for_blobs_required: true
  search_index_for_discovery_allowed: true

eventing:
  async_eventing_policy: required-when-latency-insensitive-or-cross-service
  delivery_semantics_default: at-least-once
  ordering_scope_default: per-aggregate-key
  schema_versioning_required: true
  idempotent_consumers_required: true

production:
  scalability_budget_required: true
  performance_slo_required: true
  maintainability_controls_required: true
  upgrade_strategy_required: true
  zero_downtime_upgrades_required: true
  operability_slos_required: true
